import { Property } from "@/app/(user)/dashboard/types/property";

export const featuredProperties: Property[] = [
  {
    id: "p1",
    title: "5 Katha Plot in Purbachal",
    locationText: "Sector 4, Dhaka",
    price: 20000000,
    coverImage: "/images/properties/land-1.png",
    tag: "Plain Land",
    mode: "Sell Post",
    verified: true,
  },
  {
    id: "p2",
    title: "Luxury 3 Bed Apartment",
    locationText: "Gulshan 2, Dhaka",
    price: 8075000,
    coverImage: "/images/properties/flat-1.png",
    tag: "Flat",
    mode: "Sell Post",
    verified: true,
  },
  {
    id: "p3",
    title: "Gazipur Water Zone",
    locationText: "Gazipur, Dhaka",
    price: 9512000,
    coverImage: "/images/properties/water-1.png",
    tag: "Water Land",
    mode: "Sell Post",
    verified: true,
  },
  // duplicate like screenshot (2 rows)
  {
    id: "p4",
    title: "5 Katha Plot in Purbachal",
    locationText: "Sector 4, Dhaka",
    price: 20000000,
    coverImage: "/images/properties/land-1.png",
    tag: "Plain Land",
    mode: "Sell Post",
    verified: true,
  },
  {
    id: "p5",
    title: "Luxury 3 Bed Apartment",
    locationText: "Gulshan 2, Dhaka",
    price: 8075000,
    coverImage: "/images/properties/flat-1.png",
    tag: "Flat",
    mode: "Sell Post",
    verified: true,
  },
  {
    id: "p6",
    title: "Gazipur Water Zone",
    locationText: "Gazipur, Dhaka",
    price: 9512000,
    coverImage: "/images/properties/water-1.png",
    tag: "Water Land",
    mode: "Sell Post",
    verified: true,
  },
];
