import { ManageServiceType } from "@/app/(dashboard)/admin/types/manage-service-type";

export const demoManageServiceTypes: ManageServiceType[] = [
  {
    id: "srv-1",
    name: "Ownership History Validation",
    description: "Verifying deed chain & records",
    createdAt: "20 Jan, 2026",
    isActive: true,
    icon: "doc-check",
    badgeColor: "blue",
    isMandatory: true,
  },
  {
    id: "srv-2",
    name: "Pentagraph Map",
    description: "Mapping land boundaries",
    createdAt: "20 Jan, 2026",
    isActive: true,
    icon: "map",
    badgeColor: "green",
    isMandatory: false,
  },
  {
    id: "srv-3",
    name: "Physical Estimate & Demarcation",
    description: "On-site measurements",
    createdAt: "20 Jan, 2026",
    isActive: true,
    icon: "ruler",
    badgeColor: "orange",
    isMandatory: false,
  },
  {
    id: "srv-4",
    name: "Property Registration (Dolil)",
    description: "Legal registration process",
    createdAt: "20 Jan, 2026",
    isActive: true,
    icon: "doc-pen",
    badgeColor: "purple",
    isMandatory: true,
  },
  {
    id: "srv-5",
    name: "Document Organization",
    description: "Sorting and filing deeds",
    createdAt: "20 Jan, 2026",
    isActive: false,
    icon: "folder",
    badgeColor: "teal",
    isMandatory: false,
  },
  {
    id: "srv-6",
    name: "Document Authentication",
    description: "Verifying authenticity",
    createdAt: "20 Jan, 2026",
    isActive: true,
    icon: "badge-check",
    badgeColor: "red",
    isMandatory: true,
  },
  {
    id: "srv-7",
    name: "Namjari / DCR Update",
    description: "Mutation record updates",
    createdAt: "20 Jan, 2026",
    isActive: true,
    icon: "file-up",
    badgeColor: "indigo",
    isMandatory: false,
  },
  {
    id: "srv-8",
    name: "Risk & Due-Diligence Support",
    description: "Legal risk assessment",
    createdAt: "20 Jan, 2026",
    isActive: true,
    icon: "shield",
    badgeColor: "red",
    isMandatory: true,
  },
  {
    id: "srv-9",
    name: "Full Package",
    description: "Comprehensive service bundle",
    createdAt: "20 Jan, 2026",
    isActive: true,
    icon: "package",
    badgeColor: "blue",
    isMandatory: false,
  },
];
