import { PropertyRequest } from "@/app/(dashboard)/user/types/property-request";

export const propertyRequestsData: PropertyRequest[] = [
  {
    id: "1",
    title: "3 Bed Ready Flat Needed",
    postedBy: "Farhan",
    postedAgo: "2h ago",
    code: "BUY-1042",
    location:
      "Banasree, Ward No. 25, Dhaka South City Corporation, Khilgaon Thana, Dhaka - 1219",
    propertyType: "Flat",
    requiredLandSize: "Min 5 Katha",
    requiredPlotSize: "Min 5 Katha",
    distanceFromRoad: "200m-750m",
    budgetMin: 3000000,
    budgetMax: 4000000,
  },
  {
    id: "2",
    title: "5 Bed Duplex Needed",
    postedBy: "Rahim",
    postedAgo: "5h ago",
    code: "BUY-1081",
    location: "Uttara, Sector 10, Dhaka",
    propertyType: "House",
    requiredLandSize: "Min 7 Katha",
    requiredPlotSize: "Min 7 Katha",
    distanceFromRoad: "100m-500m",
    budgetMin: 8000000,
    budgetMax: 12000000,
  },
  {
    id: "3",
    title: "Commercial Plot Needed",
    postedBy: "Ayesha",
    postedAgo: "1d ago",
    code: "BUY-1109",
    location: "Mirpur DOHS, Dhaka",
    propertyType: "Plot",
    requiredLandSize: "Min 10 Katha",
    requiredPlotSize: "Min 10 Katha",
    distanceFromRoad: "Main road",
    budgetMin: 15000000,
    budgetMax: 20000000,
  },
];
