export type createSellpostStepOneResponse = {
    id: string;
    sellerId: string;
    status: string;
    title: string;
    description: string;
    propertyType: string;
    roadDistanceMin: number;
    roadDistanceMax: number;
    sellableAmount: number;
    sellableUnit: string;
    plotSize: number;
    plotUnit: string;
    shareAmount: number;
    shareUnit: string;
    isPropertyShareable: boolean;
    askingPricePerUnit: number;
    askingPrice: number;
    division: string;
    district: string;
    upazila: string;
    unionOrCityCorp: string;
    wardNo: string;
    postalCode: string;
    fullAddress: string;
    photos: string[];
    videoUrl: string | null;
    deedFiles: string[];
    khatianFiles: string[];
    otherFiles: string[];
    selectedServices: string[];
    lastCompletedStep: number;
    createdAt: string;
    updatedAt: string;
}

export type createSellpostStepTwoResponse = {
    id: string;
    sellerId: string;
    status: string;
    title: string;
    description: string;
    propertyType: string;
    roadDistanceMin: number;
    roadDistanceMax: number;
    sellableAmount: number;
    sellableUnit: string;
    plotSize: number;
    plotUnit: string;
    shareAmount: number;
    shareUnit: string;
    isPropertyShareable: boolean;
    askingPricePerUnit: number;
    askingPrice: number;
    division: string;
    district: string;
    upazila: string;
    unionOrCityCorp: string;
    wardNo: string;
    postalCode: string;
    fullAddress: string;
    photos: string[];
    videoUrl: string | null;
    deedFiles: string[];
    khatianFiles: string[];
    otherFiles: string[];
    selectedServices: string[];
    lastCompletedStep: number;
    createdAt: string;
    updatedAt: string;
}

export type createSellpostStepThreeResponse = {
    id: string;
    sellerId: string;
    status: string;
    title: string;
    description: string;
    propertyType: string;
    roadDistanceMin: number;
    roadDistanceMax: number;
    sellableAmount: number;
    sellableUnit: string;
    plotSize: number;
    plotUnit: string;
    shareAmount: number;
    shareUnit: string;
    isPropertyShareable: boolean;
    askingPricePerUnit: number;
    askingPrice: number;
    division: string;
    district: string;
    upazila: string;
    unionOrCityCorp: string;
    wardNo: string;
    postalCode: string;
    fullAddress: string;
    photos: string[];
    videoUrl: string | null;
    deedFiles: string[];
    khatianFiles: string[];
    otherFiles: string[];
    selectedServices: string[];
    lastCompletedStep: number;
    createdAt: string;
    updatedAt: string;
}


export type submitForReviewResponse = {
    id: string;
    sellerId: string;
    status: string;
    title: string;
    description: string;
    propertyType: string;
    roadDistanceMin: number;
    roadDistanceMax: number;
    sellableAmount: number;
    sellableUnit: string;
    plotSize: number;
    plotUnit: string;
    shareAmount: number;
    shareUnit: string;
    isPropertyShareable: boolean;
    askingPricePerUnit: number;
    askingPrice: number;
    division: string;
    district: string;
    upazila: string;
    unionOrCityCorp: string;
    wardNo: string;
    postalCode: string;
    fullAddress: string;
    photos: string[];
    videoUrl: string | null;
    deedFiles: string[];
    khatianFiles: string[];
    otherFiles: string[];
    selectedServices: string[];
    lastCompletedStep: number;
    createdAt: string;
    updatedAt: string;
}
