export type BdLocation = {
  zila: string;
  thanas: string[];
};

export const BD_LOCATIONS: BdLocation[] = [
  {
    zila: "Barguna",
    thanas: [
      "Amtali",
      "Bamna",
      "Barguna Sadar",
      "Betagi",
      "Patharghata",
      "Taltali",
    ],
  },
  {
    zila: "Barishal",
    thanas: [
      "Agailjhara",
      "Babuganj",
      "Bakerganj",
      "Banaripara",
      "Gaurnadi",
      "Hizla",
      "Barishal Sadar",
      "Mehendiganj",
      "Muladi",
      "Wazirpur",
    ],
  },
  {
    zila: "Bhola",
    thanas: [
      "Bhola Sadar",
      "Burhanuddin",
      "Char Fasson",
      "Daulatkhan",
      "Lalmohan",
      "Manpura",
      "Tazumuddin",
    ],
  },
  {
    zila: "Jhalokati",
    thanas: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
  },
  {
    zila: "Patuakhali",
    thanas: [
      "Bauphal",
      "Dashmina",
      "Dumki",
      "Galachipa",
      "Kala Para",
      "Mirzaganj",
      "Patuakhali Sadar",
      "Rangabali",
    ],
  },
  {
    zila: "Pirojpur",
    thanas: [
      "Bhandaria",
      "Kawkhali",
      "Mathbaria",
      "Nazirpur",
      "Nesarabad",
      "Pirojpur Sadar",
      "Zianagar",
    ],
  },
  {
    zila: "Bandarban",
    thanas: [
      "Ali Kadam",
      "Bandarban Sadar",
      "Lama",
      "Naikhongchhari",
      "Rowangchhari",
      "Ruma",
      "Thanchi",
    ],
  },
  {
    zila: "Brahmanbaria",
    thanas: [
      "Akhaura",
      "Bancharampur",
      "Brahmanbaria Sadar",
      "Kasba",
      "Nabinagar",
      "Nasirnagar",
      "Sarail",
      "Ashuganj",
      "Bijoynagar",
    ],
  },
  {
    zila: "Chandpur",
    thanas: [
      "Chandpur Sadar",
      "Faridganj",
      "Haimchar",
      "Haziganj",
      "Kachua",
      "Matlab Dakshin",
      "Matlab Uttar",
      "Shahrasti",
    ],
  },
  {
    zila: "Chattogram",
    thanas: [
      "Anwara",
      "Banshkhali",
      "Boalkhali",
      "Chandanaish",
      "Fatikchhari",
      "Hathazari",
      "Karnaphuli",
      "Lohagara",
      "Mirsharai",
      "Patiya",
      "Rangunia",
      "Raozan",
      "Sandwip",
      "Satkania",
      "Sitakunda",
      "Chattogram Port",
      "Chattogram Kotwali",
      "Chandgaon",
      "Double Mooring",
      "Halishahar",
      "Khulshi",
      "Pahartali",
      "Panchlaish",
    ],
  },
  {
    zila: "Cumilla",
    thanas: [
      "Barura",
      "Brahmanpara",
      "Burichang",
      "Chandina",
      "Chauddagram",
      "Daudkandi",
      "Debidwar",
      "Homna",
      "Laksam",
      "Muradnagar",
      "Nangalkot",
      "Cumilla Adarsha Sadar",
      "Meghna",
      "Titas",
      "Monohorganj",
      "Cumilla Sadar Dakshin",
    ],
  },
  {
    zila: "Cox's Bazar",
    thanas: [
      "Chakaria",
      "Cox's Bazar Sadar",
      "Kutubdia",
      "Maheshkhali",
      "Ramu",
      "Teknaf",
      "Ukhia",
      "Pekua",
    ],
  },
  {
    zila: "Feni",
    thanas: [
      "Chhagalnaiya",
      "Daganbhuiyan",
      "Feni Sadar",
      "Parshuram",
      "Sonagazi",
      "Fulgazi",
    ],
  },
  {
    zila: "Khagrachhari",
    thanas: [
      "Dighinala",
      "Khagrachhari Sadar",
      "Lakshmichhari",
      "Mahalchhari",
      "Manikchhari",
      "Matiranga",
      "Panchhari",
      "Ramgarh",
    ],
  },
  {
    zila: "Lakshmipur",
    thanas: ["Lakshmipur Sadar", "Raipur", "Ramganj", "Ramgati", "Kamalnagar"],
  },
  {
    zila: "Noakhali",
    thanas: [
      "Begumganj",
      "Chatkhil",
      "Companiganj",
      "Hatiya",
      "Kabirhat",
      "Noakhali Sadar",
      "Senbagh",
      "Sonaimuri",
      "Subarnachar",
    ],
  },
  {
    zila: "Rangamati",
    thanas: [
      "Bagaichhari",
      "Barkal",
      "Kawkhali",
      "Belaichhari",
      "Kaptai",
      "Juraichhari",
      "Langadu",
      "Naniyachar",
      "Rajasthali",
      "Rangamati Sadar",
    ],
  },
  {
    zila: "Dhaka",
    thanas: [
      "Dhamrai",
      "Dohar",
      "Keraniganj",
      "Nawabganj",
      "Savar",
      "Dhaka North City Corporation",
      "Dhaka South City Corporation",
      "Gulshan",
      "Banani",
      "Dhanmondi",
      "Mohammadpur",
      "Mirpur",
      "Uttara",
      "Motijheel",
      "Ramna",
      "Lalbagh",
      "Khilgaon",
      "Shyampur",
      "Badda",
      "Tejgaon",
      "Sabujbagh",
    ],
  },
  {
    zila: "Faridpur",
    thanas: [
      "Alfadanga",
      "Bhanga",
      "Boalmari",
      "Charbhadrasan",
      "Faridpur Sadar",
      "Madhukhali",
      "Nagarkanda",
      "Sadarpur",
      "Saltha",
    ],
  },
  {
    zila: "Gazipur",
    thanas: [
      "Gazipur Sadar",
      "Kaliakair",
      "Kaliganj",
      "Kapasia",
      "Sreepur",
      "Tongi",
      "Sreepur",
      "Kaliakoir",
    ],
  },
  {
    zila: "Gopalganj",
    thanas: [
      "Gopalganj Sadar",
      "Kashiani",
      "Kotalipara",
      "Muksudpur",
      "Tungipara",
    ],
  },
  {
    zila: "Kishoreganj",
    thanas: [
      "Austagram",
      "Bajitpur",
      "Bhairab",
      "Hossainpur",
      "Itna",
      "Karimganj",
      "Katiadi",
      "Kishoreganj Sadar",
      "Kuliarchar",
      "Mithamain",
      "Nikli",
      "Pakundia",
      "Tarail",
    ],
  },
  {
    zila: "Madaripur",
    thanas: ["Kalkini", "Madaripur Sadar", "Rajoir", "Shibchar"],
  },
  {
    zila: "Manikganj",
    thanas: [
      "Daulatpur",
      "Ghior",
      "Harirampur",
      "Manikganj Sadar",
      "Saturia",
      "Shivalaya",
      "Singair",
    ],
  },
  {
    zila: "Munshiganj",
    thanas: [
      "Gazaria",
      "Lohajang",
      "Munshiganj Sadar",
      "Sirajdikhan",
      "Sreenagar",
      "Tongibari",
    ],
  },
  {
    zila: "Narayanganj",
    thanas: [
      "Araihazar",
      "Sonargaon",
      "Bandar",
      "Narayanganj Sadar",
      "Rupganj",
      "Siddhirganj",
      "Fatullah",
      "Narayanganj",
    ],
  },
  {
    zila: "Narsingdi",
    thanas: [
      "Belabo",
      "Monohardi",
      "Narsingdi Sadar",
      "Palash",
      "Raipura",
      "Shibpur",
    ],
  },
  {
    zila: "Rajbari",
    thanas: [
      "Baliakandi",
      "Goalandaghat",
      "Pangsha",
      "Rajbari Sadar",
      "Kalukhali",
    ],
  },
  {
    zila: "Shariatpur",
    thanas: [
      "Bhedarganj",
      "Damudya",
      "Gosairhat",
      "Naria",
      "Shariatpur Sadar",
      "Zajira",
      "Shakhipur",
    ],
  },
  {
    zila: "Tangail",
    thanas: [
      "Basail",
      "Bhuapur",
      "Delduar",
      "Dhanbari",
      "Ghatail",
      "Gopalpur",
      "Kalihati",
      "Madhupur",
      "Mirzapur",
      "Nagarpur",
      "Sakhipur",
      "Tangail Sadar",
    ],
  },
  {
    zila: "Bagerhat",
    thanas: [
      "Bagerhat Sadar",
      "Chitalmari",
      "Fakirhat",
      "Kachua",
      "Mollahat",
      "Mongla",
      "Morrelganj",
      "Rampal",
      "Sarankhola",
    ],
  },
  {
    zila: "Chuadanga",
    thanas: ["Alamdanga", "Chuadanga Sadar", "Damurhuda", "Jibannagar"],
  },
  {
    zila: "Jashore",
    thanas: [
      "Abhaynagar",
      "Bagherpara",
      "Chaugachha",
      "Jashore Sadar",
      "Jhikargachha",
      "Keshabpur",
      "Manirampur",
      "Sharsha",
    ],
  },
  {
    zila: "Jhenaidah",
    thanas: [
      "Harinakunda",
      "Jhenaidah Sadar",
      "Kaliganj",
      "Kotchandpur",
      "Maheshpur",
      "Shailkupa",
    ],
  },
  {
    zila: "Khulna",
    thanas: [
      "Batiaghata",
      "Dacope",
      "Dumuria",
      "Dighalia",
      "Koyra",
      "Paikgachha",
      "Phultala",
      "Rupsha",
      "Terokhada",
      "Khulna Sadar",
      "Khalishpur",
      "Sonadanga",
      "Labanchara",
      "Horintana",
    ],
  },
  {
    zila: "Kushtia",
    thanas: [
      "Bheramara",
      "Daulatpur",
      "Khoksa",
      "Kumarkhali",
      "Kushtia Sadar",
      "Mirpur",
    ],
  },
  {
    zila: "Magura",
    thanas: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
  },
  {
    zila: "Meherpur",
    thanas: ["Gangni", "Meherpur Sadar", "Mujibnagar"],
  },
  {
    zila: "Narail",
    thanas: ["Kalia", "Lohagara", "Narail Sadar", "Narail Sadar"],
  },
  {
    zila: "Satkhira",
    thanas: [
      "Assasuni",
      "Debhata",
      "Kalaroa",
      "Kaliganj",
      "Satkhira Sadar",
      "Shyamnagar",
      "Tala",
    ],
  },
  {
    zila: "Jamalpur",
    thanas: [
      "Baksiganj",
      "Dewanganj",
      "Islampur",
      "Jamalpur Sadar",
      "Madarganj",
      "Melandaha",
      "Sarishabari",
    ],
  },
  {
    zila: "Mymensingh",
    thanas: [
      "Bhaluka",
      "Dhobaura",
      "Fulbaria",
      "Gaffargaon",
      "Gauripur",
      "Haluaghat",
      "Ishwarganj",
      "Mymensingh Sadar",
      "Muktagachha",
      "Nandail",
      "Phulpur",
      "Trishal",
    ],
  },
  {
    zila: "Netrokona",
    thanas: [
      "Atpara",
      "Barhatta",
      "Durgapur",
      "Khaliajuri",
      "Kalmakanda",
      "Kendua",
      "Madan",
      "Mohanganj",
      "Netrokona Sadar",
      "Purbadhala",
    ],
  },
  {
    zila: "Sherpur",
    thanas: ["Jhenaigati", "Nakla", "Nalitabari", "Sherpur Sadar", "Sreebardi"],
  },
  {
    zila: "Bogra",
    thanas: [
      "Adamdighi",
      "Bogra Sadar",
      "Dhunat",
      "Dhupchanchia",
      "Gabtali",
      "Kahaloo",
      "Nandigram",
      "Sariakandi",
      "Sherpur",
      "Shibganj",
      "Sonatola",
    ],
  },
  {
    zila: "Joypurhat",
    thanas: ["Akkelpur", "Joypurhat Sadar", "Kalai", "Khetlal", "Panchbibi"],
  },
  {
    zila: "Naogaon",
    thanas: [
      "Atrai",
      "Badalgachhi",
      "Dhamoirhat",
      "Manda",
      "Mahadevpur",
      "Naogaon Sadar",
      "Niamatpur",
      "Patnitala",
      "Porsha",
      "Raninagar",
      "Sapahar",
    ],
  },
  {
    zila: "Natore",
    thanas: [
      "Bagatipara",
      "Baraigram",
      "Gurudaspur",
      "Lalpur",
      "Natore Sadar",
      "Singra",
    ],
  },
  {
    zila: "Chapainawabganj",
    thanas: [
      "Bholahat",
      "Gomastapur",
      "Nachole",
      "Chapainawabganj Sadar",
      "Shibganj",
    ],
  },
  {
    zila: "Pabna",
    thanas: [
      "Atgharia",
      "Bera",
      "Bhangura",
      "Chatmohar",
      "Faridpur",
      "Ishwardi",
      "Pabna Sadar",
      "Santhia",
      "Sujanagar",
    ],
  },
  {
    zila: "Rajshahi",
    thanas: [
      "Bagha",
      "Bagmara",
      "Charghat",
      "Durgapur",
      "Godagari",
      "Mohonpur",
      "Paba",
      "Puthia",
      "Tanore",
      "Rajshahi Sadar",
      "Boalia",
      "Motihar",
      "Rajpara",
      "Shah Makhdum",
    ],
  },
  {
    zila: "Sirajganj",
    thanas: [
      "Belkuchi",
      "Chauhali",
      "Kamarkhanda",
      "Kazipur",
      "Raiganj",
      "Shahjadpur",
      "Sirajganj Sadar",
      "Tarash",
      "Ullahpara",
    ],
  },
  {
    zila: "Dinajpur",
    thanas: [
      "Birampur",
      "Birganj",
      "Biral",
      "Bochaganj",
      "Chirirbandar",
      "Fulbari",
      "Ghoraghat",
      "Hakimpur",
      "Kaharole",
      "Khansama",
      "Dinajpur Sadar",
      "Nawabganj",
      "Parbatipur",
    ],
  },
  {
    zila: "Gaibandha",
    thanas: [
      "Phulchhari",
      "Gaibandha Sadar",
      "Gobindaganj",
      "Palashbari",
      "Sadullapur",
      "Sughatta",
      "Sundarganj",
    ],
  },
  {
    zila: "Kurigram",
    thanas: [
      "Bhurungamari",
      "Char Rajibpur",
      "Chilmari",
      "Phulbari",
      "Kurigram Sadar",
      "Nageshwari",
      "Rajarhat",
      "Raomari",
      "Ulipur",
    ],
  },
  {
    zila: "Lalmonirhat",
    thanas: [
      "Aditmari",
      "Hatibandha",
      "Kaliganj",
      "Lalmonirhat Sadar",
      "Patgram",
    ],
  },
  {
    zila: "Nilphamari",
    thanas: [
      "Dimla",
      "Domar",
      "Jaldhaka",
      "Kishoreganj",
      "Nilphamari Sadar",
      "Saidpur",
    ],
  },
  {
    zila: "Panchagarh",
    thanas: ["Atwari", "Boda", "Debiganj", "Panchagarh Sadar", "Tetulia"],
  },
  {
    zila: "Rangpur",
    thanas: [
      "Badarganj",
      "Gangachhara",
      "Kaunia",
      "Rangpur Sadar",
      "Mithapukur",
      "Pirgachha",
      "Pirganj",
      "Taraganj",
    ],
  },
  {
    zila: "Thakurgaon",
    thanas: [
      "Baliadangi",
      "Haripur",
      "Pirganj",
      "Ranisankail",
      "Thakurgaon Sadar",
    ],
  },
  {
    zila: "Habiganj",
    thanas: [
      "Ajmiriganj",
      "Bahubal",
      "Baniyachong",
      "Chunarughat",
      "Habiganj Sadar",
      "Lakhai",
      "Madhabpur",
      "Nabiganj",
      "Shaistaganj",
    ],
  },
  {
    zila: "Moulvibazar",
    thanas: [
      "Barlekha",
      "Juri",
      "Kamalganj",
      "Kulaura",
      "Moulvibazar Sadar",
      "Rajnagar",
      "Sreemangal",
    ],
  },
  {
    zila: "Sunamganj",
    thanas: [
      "Bishwamvarpur",
      "Chhatak",
      "Derai",
      "Dharamapasha",
      "Dowarabazar",
      "Jagannathpur",
      "Jamalganj",
      "Sullah",
      "Sunamganj Sadar",
      "Tahirpur",
    ],
  },
  {
    zila: "Sylhet",
    thanas: [
      "Balaganj",
      "Beanibazar",
      "Bishwanath",
      "Companiganj",
      "Dakshin Surma",
      "Fenchuganj",
      "Golapganj",
      "Gowainghat",
      "Jaintiapur",
      "Kanaighat",
      "Osmani Nagar",
      "Sylhet Sadar",
      "Zakiganj",
    ],
  },
]
  .map((loc) => ({
    ...loc,
    thanas: [...new Set(loc.thanas)].sort((a, b) => a.localeCompare(b)),
  }))
  .sort((a, b) => a.zila.localeCompare(b.zila));
